name: CI with Cache

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-0ee664c

      - name: prime-cache-0ee664c
        run:  echo "Cache the hit: ${{ steps.cache-step.outputs.cache-hit }}"
